### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by Ticki** [redox-os/ion#111]
Every single function should be documented, see redox-os/redox#525

**Comment by skylerberg** [comment]
What do you mean be every single function? Are we talking builtins? All public functions? Literally every single function including 1-5 liner private functions?

Also what counts as documenting it?

**Comment by mmstick** [comment]
I'm pretty sure he simply means the standard practice of ensuring that every function have documentation above the function declaration, built-in or otherwise, regardless of size.

**Comment by Ticki** [comment]
> All public functions? 

Yes.

> Literally every single function including 1-5 liner private functions?

Sure.

> Also what counts as documenting it?

3+ lines of docs (`///` comments)

**Comment by skylerberg** [comment]
I am all for documenting things every time it makes things clearer. If that means every function, so be it. However, I don't want to see documentation comments that add no information or clarity. For example, in java code it is not uncommon to see something like:
```
/**
 * @param    url    string    The URL to post to.
 */
public static post(string url) {
....
}
```

I don't want to see comments like this because they don't provide any information, they provide a place for the documentation and code to diverge, waste visual space, and waste the time of every reader. Furthermore, mandating that all functions have documentation increases the barrier to entry to creating a function, thus discouraging the good practice of writing small functions.

That said, most functions could do with a little documentation. Let's not just not be dogmatic about it.

**Comment by Ticki** [comment]
I agree.

**Comment by skylerberg** [comment]
Cool, can we make a list of things that would be good to have for documentation? I would like to start separate issues and once we feel like we have covered most everything in other issues we can close this issue. Otherwise this issue will stay open for ever because we will likely never feel like our documentation is really complete because it is an ongoing project.

**Comment by Ticki** [comment]
So I think there are three things, which needs to be exposed:

- [ ] Manual pages, for the front end user.
- [ ] API documentation (using rustdoc).
- [ ] A design document.

**Comment by skylerberg** [comment]
API documentation sounds good. For a design document, I was thinking of using the redox book to explain the design and then linking to it in the README for ion. For manpages are you thinking for the builtins or for ion itself? Normally shells don't have man pages for builtins, but they provide help that is a lot more detailed an helpful than what we have.

**Comment by skylerberg** [comment]
https://github.com/redox-os/ion/issues/114 covers API documentation.

**Comment by Ticki** [comment]
> For manpages are you thinking for the builtins or for ion itself?

From zsh man pages:

```
zsh        
zshroadmap 
zshmisc    
zshexpn    
zshparam   
zshoptions 
zshbuiltins
zshzle     
zshcompwid 
zshcompsys 
zshcompctl 
zshmodules 
zshcalsys  
zshtcpsys  
zshzftpsys 
zshcontrib 
zshall     
```

As you can see, there is quite a lot, that can be documented.

**Comment by skylerberg** [comment]
I see. Yeah there is a lot of work to do there. I opened a relevant issue: https://github.com/redox-os/ion/issues/115.

**Comment by skylerberg** [comment]
I opened an issue for the Ion chapter in the ion book. https://github.com/redox-os/book/issues/17.

**Comment by skylerberg** [comment]
Since I have separate issues for each component of this, I am closing it.
