### ISSUE TITLE
Variable expansion syntax proposition

### ISSUE THREAD

**Issue by nounoursheureux** [redox-os/ion#118]
While the current syntax `$var` is great thanks to its simplicity, I think it can be inconvenient. Here is an example in the form of an imaginary PROMPT variable:

```
let PROMPT = "$USERNAME@$CWD:$SUFFIX"
```

The problem here in my opinion is that is can be unclear when a variable's name ends. In this particular case it is easy because I used special characters, but if I wanted to use `a` instead of `@` it wouldn't work (the parser would use `$USERNAMEa` as the variable name). So i suggest that we use the following syntax instead: `${var}` . In my opinion it is as readable as `$var` while avoiding ambiguity. And so our PROMPT variable would be:

```
let PROMPT = "${USERNAME}@${CWD}:${SUFFIX}"
```

What do you think ?

**Comment by Ticki** [comment]
Personally, I would rather avoid having too easy in-string expansions.
I really dislike POSIX shell's expansion of "!", "`", and "$". Instead, I
think we should use one (and only one) sigil to denote these types of
expansions. This could be anything, for example "\".

**Comment by nounoursheureux** [comment]
Okay, so we could have something like `\{var}` to avoid using the dollar sign which is quite common.

**Comment by Ticki** [comment]
Yeah.

cc. @skylerberg.

**Comment by nounoursheureux** [comment]
@Ticki I agree that the dollar sign is widely used so it can be inconvenient to have to escape it, but `${` isn't really common so I think we could use it for string expansion.

**Comment by Ticki** [comment]
True, `${` is fine too, but having simply `$` would be quite inconvenient.

**Comment by skylerberg** [comment]
First of all let me explain how this is taken care of in Bash, because I think it is actually quite good. In Bash you the problem of ambiguous expansion is solved by *optionally* wrapping the variable in curl braces. The following is legal in bash and does what you would hope it does:
`let PROMPT = "${USERNAME}@${CWD}:$SUFFIX"`.

Next the problem of accidentally expanding within quotes is solved by having two different quoting modes. In double quotes you are using weak quoting which helps you deal with whitespace inside a token and sending globs. In this context you may still want to expand variables. If you really need something literal and has a dollar sign, then you can use single quotes, which do strong quoting. Almost everything in single quotes is taken literally.

The pros of forcing people to always use curl braces on variable expansion are that it could prevent people from accidentally expanding a variables and it could prevent them from accidentally expanding a longer variable name. The cons are that it is more verbose and it is less similar to other languages. I could see people being turned off when they see that it is somewhat inconvenient to expand a variable. Also, we would be making life more difficult for power users because they are capable of determining when to use curly braces and when not to. This leads me to think we should not require curly braces because it makes the shell slightly harder to use interactively.

I also believe we should use `$` and not some other symbol. Other choices would be arbitrarily different in a way that people would find unfamiliar. I don't see a compelling reason to do this. Dollar signs have a long strong history of use with variables. Using a `\` would probably lead to confusion and other problems because `\` is both a directory delimiter on Windows and an escape character everywhere. This reminds me of how many Windows programs used `/` instead of `-` to indicate the start of a parameter. From personal experience, I can tell you that was not a good choice.

I don't think we can necessarily use the same sigil for everything, but we can definitely unify things. Backtick syntax is not needed, for example.

**Comment by nounoursheureux** [comment]
Well, I guess it comes down to personal preferences. I would prefer to have only `${}` (I find it more readable too) and don't have to bother with strong/weak quoting most of the time, but I understand your point. I think for now we could just add the syntax with the curly braces, and let the user decide wich one they want to use.

**Comment by skylerberg** [comment]
Yep, that is what I would like to do. At some point in the future it might be worth writing a guide for writing readable scripts that would recommend sticking with the `${}` notation. I just don't want to force people to type it in an interactive session.

**Comment by choshya** [comment]
Hey! I'll try to make this my first contribution!

**Comment by vors** [comment]
The single-quote / double-quote approach that @skylerberg described is also employed in other shells (i.e. fishshell, powershell). I think it's universal enough to consider implementing it that way.

**Comment by mmstick** [comment]
@vors I've actually already implemented the double and single quoting expansions, so this is complete.

**Comment by vors** [comment]
Ah, cool :)
I also see that `${a}` syntax works as well.
Should this issue be closed then?
