### ISSUE TITLE
We should use PWD variable instead of CWD

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#146]
See discussion in https://github.com/redox-os/ion/pull/116.

**Comment by stratact** [comment]
To be honest I like CWD more, just because I think "current" is a better word than "present" but that's opinion alone.

Also the POSIX syscall that the command would use is called `getcwd()` which is standard on POSIX systems.

The Rust libstd uses `std::env::current_dir()` to get the current/present working directory as well.

The only downside is that it's not the convention from other shells, but is that really important since we're all about breaking bad conventions for better ones, as our Redox motto?

**Comment by stratact** [comment]
Just something to think about. If you guys think PWD is best, I have no problems.
