### ISSUE TITLE
Execute Function\Builtin in Subshell if in Pipeline

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#250]
Useful feature from the oil shell that makes working with pipelines more convenient. Allows for these functions to take inputs from stdin and send outputs to stdout.

**Comment by andychu** [comment]
BTW POSIX sh does this too; it's not Oil-specific.  The general idea is to run a subprogram in what I call a "thunk".  You fork but you don't exec -- you run the interpreter on a subprogram.  The fork gives you your own process with a stdin/stdout/stderr, so that you can participate in the pipeline.
