### ISSUE TITLE
Newline and tab characters do not correctly expand when escaped 

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#296]
**Reproduction**: Attempt to have Ion print out a newline or a tab as part of an escaped character in a string.

**Expected behavior**:
```
$ echo "foo \n bar"
foo
 bar
```

**Actual behavior**:
```
$ echo "foo \n bar"
foo n bar
```

**Build information**:
- `rustc -V`: `rustc 1.19.0-nightly (cfb5debbc 2017-06-12)`
- Tested on `3352a0cb` and `30deea35` 

**Blocking/related**:
- Potentially related to #292 but the first listed commit predates the PR

**Comment by mmstick** [comment]
Expected behavior should actually be:

```
$ echo "foo \n bar"
foo \n bar
$ echo -e "foo \n bar"
foo
 bar
```

It should be simple to fix this.

**Comment by huntergoldstein** [comment]
Apparently `zsh`s `echo` always interprets control sequences, regardless of flags.

What about:
```
$ echo fofof | tr "o" "\n"
````
The expected output is 
```
f
f
f
```
Right now Ion outputs
```
fnfnf
```

**Comment by mmstick** [comment]
We implement the -e argument with our implementation of echo as there would be a performance penalty in having to check echo arguments for escapes otherwise. The reason this is an issue right now is just because the parser currently removes the backslash when it's corresponding character is not a valid character for shell interpretation.

**Comment by mmstick** [comment]
This is now resolved
