### ISSUE TITLE
`calc` builtin has strange behavior when a parenthesis is the last character

### ISSUE THREAD

**Issue by huntergoldstein** [redox-os/ion#324]
**Reproduction**: Attempt to use the command:
```
calc "5 * 6 - (7 ** 3)"
```
**Expected behavior**: 
```
$ calc "5 * 6 - (7 ** 3)"
-313
```

**Actual behavior**: 
```
$ calc "5 * 6 - (7 ** 3)"
thread '<unnamed>' panicked at 'byte index 20 is out of bounds of `"5 * 6 - (7 ** 3)"`', /checkout/src/libcore/str/mod.rs:2133
note: Run with `RUST_BACKTRACE=1` for a backtrace
```
```
$ calc "5 * 6 - (4 + 4)"
<calc waits for input>
```

**Build information**:
- `rustc -V`: `rustc 1.20.0-nightly (445077963 2017-06-20)` 
- `git rev-parse HEAD`: `f16d4aef1bde530e47e956cf2c28f775a15a7b39`

**Blocking / Related**: #243

**Comment by huntergoldstein** [comment]
@mmstick Any interest in using https://github.com/Geal/nom to replace the parsers we have? They're getting increasingly complex and nom ought to be an efficient alternative.

**Comment by mmstick** [comment]
@huntergoldstein If you'd like to try out **nom**, you may. My main reason for choosing to write the shell logic by hand was that A) parsing frameworks had limited in expressiveness at the time, B) also incurred overhead compared to manually writing them by hand, and C) was very complicated to figure out how to use them to parse all the different possible expressions correctly.

As a fun fact: most of the original shell logic was implemented in PEG initially, but no one could figure out how to get it to parse shell expressions correctly besides very simple expressions, and I couldn't figure it out myself. So, as the months passed and no progress was made, I decided to re-implement everything by hand, and we finally started making huge leaps in progress, in a relatively short timeframe.

In the end, I've found that writing parsing as it is written in the **shell_expand::words** module has been the most effective way to write the parsing for the shell. I'd eventually like to rewrite the **parser::statements** and **parser::pipelines** modules in the same image as the **words** module, and then possibly replace what remains of PEG entirely, as it doesn't give us the kind of error messages and flexibility that we'd like.

**Comment by mmstick** [comment]
While we are also talking about Calc though, I've been wondering if we could implement expressions like so:

```ion
calc 'log 10'
1
calc 'cos 10'
0.984807753
```

**Comment by huntergoldstein** [comment]
To qualify my complaints, it is mainly `parser::statements` that frustrated me while working on this. PEG doesn't seem any different from other parser generators like `yacc` or `menhir`. Nom is closer to `parsec` on that note. Also: what kind of error messages / flexibility specifically does Ion need?

**Comment by mmstick** [comment]
`parser::statements`, and especially `parser::pipelines`, are a piece of work. They are monolithic parsers that are trying to do all the parsing in the same loop, and thus are quite probably heavy on CPU and mental burden to handle different scenarios. Not easy to expand at all, and requires many more bit flags than we need. We could easily switch them over to performing nano-parsing like `shell_expand::words` though.

I'm guessing you were having some issue with getting the `((` and `))` syntax read correctly. I'd just do a check whenever the `(` character is found and `COMM_ONE` is set on the next character, which can be obtained by grabbing that byte with the `self.read` index. If it's also a `(`, up an `arith_level` counter, otherwise up the `process_level`. Similar approach for the `)` character.

The kinds of error messages that we want are nice, simple custom error messages, like `ion: syntax error: variable in for loop contains invalid characters`. Currently, we just get a ugly and verbose error message if you happen to generate an error in PEG.

**Comment by huntergoldstein** [comment]
It would definitely be worthwhile to switch those over, if only for readability reasons.

That sounds roughly like what I ended up doing.

I'll play around with nom, see if the error messages are comparable to the custom ones.

**Comment by mgmoens** [comment]
I was thinking about nom as well. Could we decouple calc (for instance) in a crate and try out nom there? Else I was thinking about the shell expand module. I've dipped my toes into nom already, simple parsing should be doable. I might try something \w nom tomorrow,  but I'll be unavailable for more than two weeks starting tuesday. Biggest problem with nom is the lacking documentation for the 2.0+ versions, but I have figured out a simple parser already.

 I have a feeling I've introduced this bug :)

**Comment by huntergoldstein** [comment]
I also would like to decouple `calc`; let's move this to an open issue.

**Comment by mmstick** [comment]
It was originally my goal to see `calc` split as a library on it's own. I copied the source code from [redox-os/extrautils](https://github.com/redox-os/extrautils/blob/master/src/bin/calc.rs) and then sort of slightly repurposed it for Ion.
