### ISSUE TITLE
double escaping

### ISSUE THREAD

**Issue by aeosynth** [redox-os/ion#348]
touch '(x)'
    rm \(<Tab> # rm \\(x\)
    ion: syntax error: '(' at position 6 is out of place

**Comment by huntergoldstein** [comment]
Same as #347.

**Comment by aeosynth** [comment]
this issue persists

**Comment by huntergoldstein** [comment]
Oh my mistake: I read the input as `rm <Tab>` versus `rm \(<Tab`. Yes I can confirm this is still a problem on master (it was probably a problem before).

**Comment by huntergoldstein** [comment]
So the problem comes down to `liner`'s default word splitting function ([as seen here](https://github.com/MovingtoMars/liner/blob/3a5c45d4b2fd93ef49b8dffe91a6312c11c0fdaf/src/context.rs#L9)). What happens is the following:
1. We ask liner to complete the current word
2. Liner uses the default splitting function and comes up with `(` as the current word, as the leading backslash is skipped
3. Liner then replaces that word with `\(x\)`, based on its internal completer
4. Because the leading backslash is not part of the word, `\\(x\)` ends up being written.

There's a slightly larger issue here too, which is that any completion that has escapes in it will not work. For example:
```
$ touch 'f(x)'
$ rm f\(<Tab>
```
will do nothing.
