### ISSUE TITLE
Execute Builtins Within Pipeline Execution

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#379]
If a builtin needs to be piped, we should do precisely that. We should achieve this by creating new file descriptors, and mapping the stdout and stderr of these builtin commands to these file descriptors.

**Comment by mmstick** [comment]
A reminder to [notify a Reddit user](https://www.reddit.com/r/linux/comments/6ndeed/try_out_the_ion_shell_a_nix_shell_written_in_rust/dk9qce6/) when this is finished.

**Comment by mmstick** [comment]
Builtin commands will need to have their parameters changed to the following for this to work:

```rust
builtin (
    shell: &mut Shell,
    args: &[&str],
    stdin: Option<RawFd>,
    stdout: Option<RawFd>,
    stderr: Option<RawFd>,
)
```

When a FD is set to `None`, inherit the shell's FD for that field. Usage of `io::{stdout(),stdin(), stderr()}` within a builtin function should generally forbidden.

**Comment by huntergoldstein** [comment]
Wouldn't it make more sense to have `stdout` et al be `Option<Stdio>`? That way the built-in won't have to be `unsafe` unless it needs to be, otherwise you'd be passing around `RawFd`s.

**Comment by mmstick** [comment]
That might make more sense.

**Comment by huntergoldstein** [comment]
Actually I'm not so sure: we'd be using `stdout` et al as streams to read from or write to. `Stdio` doesn't allow that.

**Comment by mmstick** [comment]
So `RawFd` it may be then, as we can open them via `File::from_raw_fd()`.

**Comment by huntergoldstein** [comment]
IMO this would be the right way to fix #454.

Right now the logic in `shell::pipe::pipe` requires a list of `(Command, JobKind)`s. One idea is to have some type that abstractly represents a shell command, builtin, etc. but provides roughly the same interface as `Command`. Thoughts? Clarifications?

**Comment by mmstick** [comment]
That's been my idea for solving this. A two step process:

1. Modify builtin parameters to set the FDs for stdin/stdout/stderr.
2. Move them into pipeline execution and create a new `IonCommand` abstraction
  - **IonCommand** could be either a builtin or external command
  - Then maybe even functions could be treated as commands

**Comment by huntergoldstein** [comment]
I'll continue to hack away at this. Should be doable throughout tomorrow. I'm thinking functions can be done much like built-ins but I'll limit the scope of the incoming PR.

**Comment by huntergoldstein** [comment]
Minimal progress here: https://github.com/huntergoldstein/ion/tree/pipeline_builtins
- Because Ion gets `fork`'d, builtins with side-effects will do nothing; I'm pretty sure this isn't a problem
- I'm not sure about the fields for the `RefinedJob::Builtin` being `RawFd`; it might be better down the road to use something that's not in the `sys::os::unix` module or at least restrict its use.

**Comment by huntergoldstein** [comment]
More progress made today:
- I had to use `wait` instead of `waitpid`; it seems there's a race condition where if the child process exits before the parent can wait on it, `waitpid` will return `ECHILD`, and not properly set the exit status. This was a problem for cases like `examples/conditionals.ion`
- I'm able to pipe from aliases into other programs, but the last process fails to terminate. I remember running into this when working on #331.

**Comment by huntergoldstein** [comment]
Still working on this; I think [this is the problem](https://stackoverflow.com/questions/3910253/c-c-trying-to-force-eof-from-parent-process-sending-input-to-child-process). I spent yesterday trying to analyze the difference between `Command::spawn` and what I do manually and I think its just that Rust uses `CLOEXEC`, such that the lifetime of the pipes is determined by the parent holding onto them, not the child. Need to test.

**Comment by mmstick** [comment]
I had that issue when fixing the SIGPIPE problem of piped command. Fixed it with a callback that drops the Commands when a detected child quits.
