### ISSUE TITLE
Subshells Should Fork

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#424]
Currently, Ion pre-expands subshell expressions before creating a new Ion process and handing it the expanded form. Instead, we should properly fork the shell at this point, and get rid of all the logic for handling shell expansion pre-expansions. This means that, currently, the following doesn't work:

```ion
fn test; echo testing; end
echo $(test)
```

**Comment by drosseau** [comment]
I'm trying to find a nice fix for this but it is getting kinda messy. I think the problem is complicated by the fact that expansion isn't handled by the `Shell` but by a bunch of closures over the variables and directory stack, so when you get to `command` you have no access to the `Shell`. I think it'd make this easier and make more sense if the expand functions functions were actually implemented by `Shell` so we didn't have to use the closures and the `get_expanders!` macro. That'd be a lot of refactoring though.

**Comment by huntergoldstein** [comment]
I believe that's what `ExpandFunctions::command` is for no? It might be nice to encapsulate the subshell logic so that running methods / builtins in forks can share all that same code.

I played around with making `ExpandFunctions` a trait instead of a struct. To me it _feels_ better* and it wouldn't require a ton of refactoring.

* Read: more idiomatic in my admittedly limited experience

**Comment by drosseau** [comment]
`command` doesn't know about any of the user defined functions and just creates a new ion process to run the command, similar to how builtins were working before. That is why his example isn't working. I played around with the same thing but, I ended up needing to do a decent amount of refactoring and scrapped my approach. Haven't had time to look at it for a while though.

**Comment by mmstick** [comment]
Access can be granted to builtins and functions by just adding their associated fields to the expander.

**Comment by huntergoldstein** [comment]
Making `ExpanderFunctions` into an `Expander` trait might be a slightly nicer way such that `command` can know about builtins / functions (by passing, say, `Shell` as `&self`). 

An intermediate step could be to have `ExpanderFunctions` implement `Expander` as many tests create their own special instances of `ExpanderFunctions`. I tried this, but it felt messy and I'd rather just scrap `ExpanderFunctions` (and especially `get_expanders!` altogether).

**Comment by huntergoldstein** [comment]
I've been hacking away at the above for a good bit of today; getting rid of `ExpanderFunctions` altogether is a little tougher as a lot of tests use their own special versions, but I think a sensible thing to do is to have any `Expander` trait have its functions return `None` by default then each test can implement something like:
```
struct LocalExpand;

impl Expander for LocalExpand {
  fn variable(...) -> Option<Value> {
    // match against known set of variables
  }
}
```
This pattern shows up a lot so we could create a macro / struct specifically for this occurrence.

**Comment by huntergoldstein** [comment]
I'm going to move on to a different issue after playing with this for a bit: some notes:
- Because `Expander::command` takes an immutable reference to `Self`, this will be tricky as most of the logic for evaluating a command takes a mutable reference to `Self`. One could, probably, do a grep for `&E\b` and replace it with `&mut E` but I'm of the opinion that the `Expander` methods ought to not have sight effects.
- The fork logic looked really similar to that in `Shell::run_pipeline` (?), which meant another mess of `sys::close`; it might be fruitful to add Redox support to [`os_pipe`](https://github.com/oconnor663/os_pipe.rs) which I am playing around with

**Comment by mmstick** [comment]
[I've implemented this](https://github.com/redox-os/ion/commit/1147ac5785c7170ab241c14df34988fd797f860d).

**Comment by mmstick** [comment]
@huntergoldstein The way I solved this was just by storing an `*mut Shell` pointer before doing the expansions, and then using that pointer in the child to get mutable access to the child's shell. Seemed to be the only way to go about solving this, and it's relatively straight forward.

The only issue I've yet to solve is getting the child to have stdin support. If I don't close stdin in the child, the parent's stdin will hang.
