### ISSUE TITLE
Parsing Issue w/ && Operator

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#454]
I'm not sure why this is at the moment, but:

```sh
matches Foo '([A-Z])\w+' && echo true
```

Gives the following output:

```
ion: syntax error: '(' at position 13 is out of place
```

But this:

```sh
matches Foo '([A-Z])\w+'; echo true
```

Gives:

```
true
```

I've also noticed that this:

```sh
matches Foo '[A-Z]\w+' && echo true
```

Gives no output, but this does:

```sh
matches Foo '[A-Z]\w+'; echo true
```

Likely the same issue, and likely in the `StatementSplitter` logic.

**Comment by huntergoldstein** [comment]
Taking a look at this now. I think the problem is how `'([A-Z])\w+'` is passed from the main process to the fork. If I print out the input to `StatementSplitter`, I see:
```
matches Foo '([A-Z])\w+' && echo true
matches Foo ([A-Z])\w+
```
We lose the information that the second argument was single quoted. This doesn't happen when we run `matches Foo '([A-Z])\w+'; echo true` as this is just run as two statements and encounters [this branch](https://github.com/redox-os/ion/blob/0d8af9d76b04ddeb0ac060a85e4a05c6f8dca452/src/shell/mod.rs#L174).
