### ISSUE TITLE
Calling cd (a builtin) from an alias

### ISSUE THREAD

**Issue by anxiousmodernman** [redox-os/ion#622]
In zsh I often create this alias to **u** to jump to my parent directory:

```zsh
alias u="cd .."
```

I've tried a few variants in ion, but I can't get it to work. My guess is that alias executes a subprocess that has state independent of the parent process (the current shell).

#409 has `exec` on the TODO list. Is exec the blocker to doing something like this in ion? A related design question might be: after exec is implemented, should all aliases be `exec`'d? E.g., aliases would be more like a macro that replaces characters and can modify the running shell's state.

**Comment by mmstick** [comment]
No, `exec` is something different. The `cd` builtin would not work with that either, because `cd` is not an external command, but a builtin pseudo-command that works by changing the shell's internal `$PWD`. Other processes have no ability to change variables in the shell.

I think there's just a missing logical step to check the type of command that is stored in the expanded form of the aliased command. There should be a check to see whether it's a builtin, external, etc. Yet what's happening is that there is no such check, and it's automatically thereby assumed that the expanded command is an external command.

The fix is pretty simple, for anyone that would like to look into it. I'm busy with another project at the moment.

**Comment by anxiousmodernman** [comment]
Thanks for the feedback. I think I have a fix for this. I will open a PR.
