### ISSUE TITLE
Quote-Related Parsing Issue

### ISSUE THREAD

**Issue by mmstick** [redox-os/ion#640]
### Input

```
echo "\$test"
```

### Expected

```
$test
```

## Actual

```
\$test
```

**Comment by covercash2** [comment]
this issue is closely related to #641 in that macOS has different behavior. 

initrc:

    fn PROMPT
	    printf "${USER}\@$(hostname)\n > "
    end

in the source, i added a println [here](https://github.com/redox-os/ion/blob/49fba94a6c8738b9c77b6cf059e8c4d6871fdb7d/src/shell/pipe_exec/mod.rs#L751) in shell/pipe_exec/mod.rs fn pipe, i.e.:

`eprintln!("parent: {}", parent.long());`

macOS output:

    parent: hostname
    parent: printf user\\@mac\\ > "  
    user@mac
     > printf "\$hello\n"
    parent: printf \\$hello\\n
    $hello
    parent: hostname
    parent: printf user\\@mac\\ > "
    user@mac
     > echo "\$hello"
    \$hello
    
debian output:

    parent: hostname
    parent: printf user\\@nix\\ > "
    user\@nix
     > printf "\$hello\n"
    parent: printf \\$hello\\n
    \$hello
    parent: hostname
    parent: printf user\\@nix\\ > "
    user\@nix
     > echo "\$hello"
    \$hello

the interesting part is that on macOS printf does the right thing but echo doesn't. and on linux both printf and echo fail to escape correctly.

there's probably a clue in that fact.
