### ISSUE TITLE
Panic when using comments in the array initializer 

### ISSUE THREAD

**Issue by xTibor** [redox-os/ion#642]
**Reproduction**:
```
let x = [
a
# b
# c
]
```

**Actual behavior**:
A panic with the following error message: `thread 'main' panicked at 'ion: fatal error with syntax validation: unterminated array expression', src/parser/shell_expand/words/mod.rs:555:8
`
[Backtrace](https://gist.github.com/xTibor/55559a9ec02489b9a74ec56e0f906cb8)

**Build information**:
`rustc -V`: `rustc 1.24.0-nightly (c8ddf2852 2017-12-07)`
`git rev-parse HEAD`: c6bdc75cbf3152b3dc3ddfe20c81c73d26f28899
System: KDE neon 5.11 (Ubuntu 16.04 LTS)

**Comment by lausek** [comment]
The bug seems to appear in `shell/binary/terminate.rs` on line 13 which tries to transform multiline statements into one buffer, so this:

```
let x = [
a
# b
# c
]
```
will end up as this `let x = [ a #b #c ]` and the closing bracket will be lost. I quick-and-dirty-fixed the code above by inserting this before the append: 
``` if let Some(_) = command.find('#') { continue; }  ```

But me must obviously consider splitting out everything in front of the pound and we have to take care of multiline strings too.

**Comment by mmstick** [comment]
@lausek The terminator strips out everything beyond the **#** character, so it shouldn't expand to that. This can be observed when you write comments in-line like so:

```ion
let x = [
    a # a comment
    b
    c # another comment
]
```

This will be converted into `let x = [ a b c ]`.

The issue here seems to be regarding having the first character in the input as a **#**.

**Comment by mmstick** [comment]
Am going to look into this, and add some integration tests.

**Comment by mmstick** [comment]
Just got home, and I'm about to push a commit to fix this.
