### ISSUE TITLE
Make Homu run rustfmt on repo before merge

### ISSUE THREAD

**Issue by skylerberg** [redox-os/ion#78]
Obviously this depends on https://github.com/redox-os/ion/issues/77.

**Comment by MovingtoMars** [comment]
Even before this is implemented, it would be nice to just have `rustfmt` run over the repo manually now.

My editor runs `rustfmt` on save, and it causes a lot of format changes. This is annoying because I have to run `git add -p` to manually select only changes relevant to the commit so the commit isn't messy.
